### ISSUE TITLE
Distortions_in_the_experiment_simulations

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#1]
When animation is going on an 'x' element,  if we click on an other element to animate, the current animation is getting stopped in the middle and creating position distortions in the experiment. Due to this whole experiment functionality is getting disturbed. 

This is the issue in all the 10 experiments.

**Comment by sravanthimodepu** [comment]
Issue is fixed.
