### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy_Expt-7_Simulation_Instruction slot

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#103]
Defect Description:
The Simulation page of "Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity: Determination of Unknown Concentration of an Analyte" experiment of this lab, the scrollbar is moving according to the length of the instruction. Which is not proper. Need to fix the placing of the scrollbar.   

Actual Result :
The Simulation page of "Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity: Determination of Unknown Concentration of an Analyte" experiment of this lab, the scrollbar is moving according to the length of the instruction. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte_20_Simulation_Instruction_p1.org

Attachment:
![qa_mfs_i99](https://cloud.githubusercontent.com/assets/13479177/22100020/ba7204aa-de53-11e6-8272-aa1428e09d88.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #103
