### ISSUE TITLE
QA_MFS_Expt-4_Theory_Improper alignment for the table

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#137]
Defect Description:
The Theory page of " Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore" experiment of this lab, improper alignment is observed for the table. In order to maintain the look and feel of the page need to correct the alignment. 

Actual Result :
The Theory page of " Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore" experiment of this lab, improper alignment is observed for the table. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore_04_Theory_smk.org

Attachment:
![qa_mfs_i116](https://cloud.githubusercontent.com/assets/13479177/22502443/db85c21e-e892-11e6-8647-7fa9e3b17f35.png)

**Comment by sadhanareddy** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #137
