### ISSUE TITLE
QA_MFS_Expt-7_Simulation_wrongly given

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#149]
Defect Description:
The simulation page of " Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity- Determination of Unknown Concentration of an Analyte " experiment of this lab, is wrongly ported with the experiment of "Effects of Fluorophore Concentration on Fluorescence Spectra: Inner Filter Effects"

Actual Result :
The simulation page of " Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity- Determination of Unknown Concentration of an Analyte " experiment of this lab, is wrongly ported with the experiment of "Effects of Fluorophore Concentration on Fluorescence Spectra: Inner Filter Effects"

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte_11_Simulation_smk.org

Attachment:
![qa_mfs_i127](https://cloud.githubusercontent.com/assets/13479177/22505273/97cbf71a-e8a0-11e6-9ea4-29d512f89ef5.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #149
