### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy_Expt-1_Quiz_Unwanted characters.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#15]
Defect Description:
The Quiz page of "Introduction to the fluorescence spectroscopy principle" experiment of this lab,found unwanted characters in 7th question and the brace given for the hint is not closed in this point.

Actual Result :

The Quiz page of "Introduction to the fluorescence spectroscopy principle" experiment of this lab,found unwanted characters in 7th question and the brace given for the hint is not closed in this point.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Introduction-to-the-fluorescence-spectroscopy-principle/Introduction-to-the-fluorescence-spectroscopy-principle_06_Quiz_smk.org

Attachment:
![qa_mfs_i13](https://cloud.githubusercontent.com/assets/13479177/21974361/49e44f90-dbec-11e6-9048-525d3cde2423.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Removed the unwanted character.

**Comment by BSravanthi** [comment]
Closed #15
