### ISSUE TITLE
 QA_Molecular Fluorescence Spectroscopy Lab_all experiments_cursor 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#2]
Defect Description :
In all the simulations of "Molecular Fluorescence Spectroscopy Lab", the cursor is changing for all the objects instead, the mouse pointer should be changed according to the process of the experiment. According to the simulation process the mouse pointer should change on the desired object. But in all the experiments of this lab irrespective of the procedure the mouse pointer is getting changed to the cursor for all the objects.

Actual Result :
In all the simulations of "Molecular Fluorescence Spectroscopy Lab", the cursor is changing for all the objects instead, the mouse pointer should be changed according to the process of the experiment. According to the simulation process the mouse pointer should change on the desired object. But in all the experiments of this lab irrespective of the procedure the mouse pointer is getting changed to the cursor for all the objects.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
Closed #2
