### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_Spelling mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#3]
Defect Description :
During the smoke test, found spelling mistakes in all the pages of this lab. 

Actual Result :
During the smoke test, found spelling mistakes in all the pages of this lab. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration: 8GBRAM,
Processor:i5

Attachments: 
[MFS.zip](https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/files/684452/MFS.zip)

**Comment by sadhanareddy** [comment]
Issue is fixed. Corrected the mistakes.

**Comment by BSravanthi** [comment]
closed #3
