### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_Introduction to the fluorescence spectroscopy principle_Simulation_Experiment is not provided.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#4]
Defect Description:
In ”Introduction to the fluorescence spectroscopy principle” experiment, when we click on the "Click here to view the principle" link, no experiment is provided to perform. Instead a new tab with the experiment provided should be opened. 

Actual Result :
In ”Introduction to the fluorescence spectroscopy principle” experiment, when we click on the "Click here to view the principle" link, no experiment is provided to perform.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Introduction-to-the-fluorescence-spectroscopy-principle/Introduction-to-the-fluorescence-spectroscopy-principle_11_Simulation_smk.org

Attachment:
![qa_mfs_i1](https://cloud.githubusercontent.com/assets/13479177/21803050/5563f098-d74e-11e6-859b-932ee94b4225.png)

**Comment by sadhanareddy** [comment]
Experiment is getting opened on clicking the link. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #40
