### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy_Familiarization with the fluorescence Instrumentation_Simulation_link_navigating to wrong page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#5]
Defect Description:
In ”Familiarization with the fluorescence Instrumentation” experiment, when we click on the " Click here to study the mirror image and stoke shift" link, the link is redirecting to a wrong page. Where as the link should be navigated to concerned page provided with the study reference of study the mirror image and stoke shift.

Actual Result :
In ”Familiarization with the fluorescence Instrumentation” experiment, when we click on the " Click here to study the mirror image and stoke shift" link, the link is redirecting to a wrong page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Familiarization-with-the-fluorescence-Instrumentation/Familiarization-with-the-fluorescence-Instrumentation_11_Simulation_smk.org

Attachment:
![qa_mfs_i2](https://cloud.githubusercontent.com/assets/13479177/21803233/2f0cdfda-d74f-11e6-91c5-f6241943cecd.png)

**Comment by sadhanareddy** [comment]
Experiment is getting opened on clicking the link. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #5
