### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_home page_Onclick_logo

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#6]
Defect Description:
In the Home page of the "Molecular Fluorescence Spectroscopy Lab", on click, the Virtual lab logo is navigating to an Error page. Instead the link should lead to the home page of the virtual lab web page.

Actual Result :
In the Home page of the "Molecular Fluorescence Spectroscopy Lab", on click, the Virtual lab logo is navigating to an Error page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/tree/master/test-cases/integration_test-cases

Attachment:
![qa_mfs_i3](https://cloud.githubusercontent.com/assets/13479177/21888688/5b131534-d8eb-11e6-9ebc-035f9e3e7652.png)

**Comment by sadhanareddy** [comment]
After a discussion with Lalit, came to a conclusion that, these issues need not to be fixed as the content of the lab will be ported to open edx.
While redirection of the links of the lab to openedx, they were broken. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #6
