### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_Home page_on click_All labs

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#7]
Defect Description:
In the Home page of the "Molecular Fluorescence Spectroscopy Lab", on click, the "All Labs" link is navigating to an Error page. Instead the link should lead to the page where the user can be able to browse the list of all available labs from virtual labs.

Actual Result :
In the Home page of the "Molecular Fluorescence Spectroscopy Lab", on click, the "All Labs" link is navigating to an Error page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/tree/master/test-cases/integration_test-cases

Attachment:
![qa_mfs_i4](https://cloud.githubusercontent.com/assets/13479177/21888827/fd82faaa-d8eb-11e6-9302-33cfaa6ecc49.png)

**Comment by sadhanareddy** [comment]
After a discussion with Lalit, came to a conclusion that, these issues need not to be fixed as the content of the lab will be ported to open edx.
While redirection of the links of the lab to openedx, they were broken. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #7
