### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy_Home page_Acknowledgement_Discipline name slot is given with the lab's name

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#8]
Defect Description:
In the "Acknowledgement" link in the Home page of the "Molecular Fluorescence Spectroscopy Lab", the discipline slot is given with this lab name itself. Where as this slot should be provided with name of the concerned discipline name, ie Chemical Sciences.

Actual Result :
In the "Acknowledgement" link in the Home page of the "Molecular Fluorescence Spectroscopy Lab", the discipline slot is given with this lab name itself. Where as this slot should be provided with name of the concerned discipline name, ie Chemical Sciences.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/tree/master/test-cases/integration_test-cases

Attachment:
![qa_mfs_i5](https://cloud.githubusercontent.com/assets/13479177/21889783/a075de5e-d8f0-11e6-8e93-ba295d725120.png)

**Comment by sadhanareddy** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #8
