### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy_Home page_Experiments_Discipline name slot is given with the lab's name

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#9]
Defect Description:
The "Experiments" link in the Home page of the "Molecular Fluorescence Spectroscopy Lab", the discipline slot is given with this lab name itself(Molecular Fluorescence Spectroscopy). Where as this slot should be provided with name of the concerned discipline name, ie Chemical Sciences. More over the given lab link is redirecting to error page.  

Actual Result :
In the "Acknowledgement" link in the Home page of the "Molecular Fluorescence Spectroscopy Lab", the discipline slot is given with this lab name itself. Where as this slot should be provided with name of the concerned discipline name, ie Chemical Sciences. And the given lab link is redirecting to error page.  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/tree/master/test-cases/integration_test-cases

Attachment:
![qa_mfs_i6](https://cloud.githubusercontent.com/assets/13479177/21971236/b5deb8e2-dbd4-11e6-8d43-3f6a6cb040b8.png)

**Comment by sadhanareddy** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #9
