### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_Expt-3_Simulation_Solvent selection bar

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#92]
Defect Description:
In the ”Familiarization with Excitation and Emission Spectra, Mirror Image Relation and Stokes Shift” experiment, when we reset the experiment the solvent section bar being hidden. If we click on Flask with out choosing the solution from the solvent selection bar a dialogue box is appearing with a warning message. Once the experiment is restarted the solvent section bar should start its functionality. Need to fix the issue in order to maintain the functionality of the experiment. 

Actual Result :
In the ”Familiarization with Excitation and Emission Spectra, Mirror Image Relation and Stokes Shift” experiment, when we reset the experiment the solvent section bar being hidden. If we click on Flask with out choosing the solution from the solvent selection bar a dialogue box is appearing with a warning message. Once the experiment is restarted the solvent section bar should start its functionality.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Familiarization-with-Excitation-and-Emission-Spectra-Mirror-Image-Relation-and-Stokes-Shift/Familiarization-with-Excitation-and-Emission-Spectra-Mirror-Image-Relation-and-Stokes-Shift_12_Simulation_UI_p1.org

https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Familiarization-with-Excitation-and-Emission-Spectra-Mirror-Image-Relation-and-Stokes-Shift/Familiarization-with-Excitation-and-Emission-Spectra-Mirror-Image-Relation-and-Stokes-Shift_13_Simulation_Slider-bar_p1.org

Attachment:
![qa_mfs_i89](https://cloud.githubusercontent.com/assets/13479177/22060636/983e6f20-dd97-11e6-8639-e30a77551157.png)

**Comment by sadhanareddy** [comment]
Its, because without choosing the solution from the solvent selection bar, if tried to perform the experiment a warning mesage gets displayed to select the solution to perform the experiment.

**Comment by BSravanthi** [comment]
Closed #92
