### ISSUE TITLE
QA_Molecular Fluorescence Spectroscopy Lab_Expt-4_Simulation_Solvent selection bar

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith#94]
Defect Description:
In the ”Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore” experiment, the slider bar is not getting enabled when we click on "reset" button. The experiment can not be move further with out selecting the solution. Hence the slider bar should be enabled in order to finish the experiment by the user, even after the user wants to re start the experiment. 

Actual Result :
In the ”Demonstration of Solvent Effects on Fluorescence Spectra of a Fluorophore” experiment, the slider bar is not getting enabled when we click on "reset" button. The experiment can not be move further with out selecting the solution. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore_12_UI_smk.org

https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore/Demonstration-of-Solvent-Effects-on-Fluorescence-Spectra-of-a-Fluorophore_13_Selection-bar_p1.org

Attachment:
![qa_mfs_i91](https://cloud.githubusercontent.com/assets/13479177/22061883/fddb9bfa-dd9c-11e6-97e4-4f65890ed37c.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Slider bar is getting enabled, after clicking on the reset button.

**Comment by BSravanthi** [comment]
Closed #94
